# Generated by Django 5.2.2 on 2026-06-13 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('holes', models.PositiveIntegerField(default=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sprinkler_duration', models.PositiveIntegerField(default=45, help_text='Minutes per zone')),
                ('water_source', models.CharField(blank=True, choices=[('municipal', 'Municipal supply'), ('borewell', 'Borewell / groundwater'), ('recycled', 'Recycled greywater'), ('rainwater', 'Rainwater harvesting')], max_length=50)),
                ('irrigation_schedule', models.CharField(blank=True, choices=[('early_morning', 'Early morning only'), ('morning_evening', 'Morning & evening'), ('continuous', 'Continuous cycles'), ('on_demand', 'On-demand / manual')], max_length=50)),
                ('moisture_sensors', models.CharField(blank=True, choices=[('none', 'None'), ('partial', 'Partial coverage'), ('full', 'Full coverage')], max_length=20)),
                ('chemical_frequency', models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('biweekly', 'Every two weeks'), ('monthly', 'Monthly'), ('seasonal', 'Seasonal / as needed')], max_length=20)),
                ('pest_control_method', models.CharField(blank=True, choices=[('broad_spectrum', 'Broad-spectrum pesticides'), ('targeted', 'Targeted treatments'), ('biological', 'Biological control'), ('mixed', 'Mixed approach')], max_length=30)),
                ('weed_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('pest_severity', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('severe', 'Severe')], max_length=20)),
                ('species_observed', models.JSONField(blank=True, default=list)),
                ('mowing_frequency', models.PositiveIntegerField(default=4, help_text='Times per week')),
                ('team_size', models.CharField(blank=True, choices=[('1-5', '1–5'), ('6-12', '6–12'), ('13-25', '13–25'), ('25+', '25+')], max_length=10)),
                ('energy_source', models.CharField(blank=True, choices=[('petrol_diesel', 'Petrol / diesel'), ('mixed', 'Mixed fleet'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20)),
                ('labour_availability', models.CharField(blank=True, choices=[('limited', 'Limited'), ('adequate', 'Adequate'), ('seasonal', 'Seasonal shortage')], max_length=20)),
                ('sustainability_score', models.PositiveIntegerField(blank=True, null=True)),
                ('water_savings_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('estimated_cost_saving_monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('biodiversity_risk', models.CharField(blank=True, max_length=20)),
                ('chemical_dependency', models.CharField(blank=True, max_length=20)),
                ('priority_recommendation', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('greens', 'Greens'), ('water_body', 'Water body'), ('rough_patch', 'Rough patch'), ('pest_zone', 'Pest zone'), ('other', 'Other')], default='other', max_length=20)),
                ('image', models.ImageField(upload_to='course_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10)),
                ('estimated_cost', models.CharField(max_length=100)),
                ('benefit', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.assessment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
